#!/bin/zsh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$PROJECT_DIR/.." && pwd)"
TP_DIR="$PROJECT_DIR/third_party/gdal_core_minimal"
SRC_DIR="$TP_DIR/src"
TMP_DIR="/tmp/ofgdb-gdal-core-import"
GDAL_TAG="v3.12.0"
ARCHIVE_URL="https://github.com/OSGeo/gdal/archive/refs/tags/${GDAL_TAG}.tar.gz"
ARCHIVE_FILE="$TMP_DIR/gdal.tar.gz"
SHARED_ARCHIVE_CACHE="/tmp/ofgdb-gdal-import/gdal.tar.gz"
LOCAL_ARCHIVE_CACHE="/tmp/ofgdb-gdal-cache/gdal-${GDAL_TAG}.tar.gz"

rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR" "$SRC_DIR"

if [[ -n "${OPENFGDB4J_GDAL_ARCHIVE:-}" && -f "${OPENFGDB4J_GDAL_ARCHIVE}" ]]; then
  cp "${OPENFGDB4J_GDAL_ARCHIVE}" "$ARCHIVE_FILE"
elif [[ -f "$SHARED_ARCHIVE_CACHE" ]]; then
  cp "$SHARED_ARCHIVE_CACHE" "$ARCHIVE_FILE"
elif [[ -f "$LOCAL_ARCHIVE_CACHE" ]]; then
  cp "$LOCAL_ARCHIVE_CACHE" "$ARCHIVE_FILE"
else
  curl -fL "$ARCHIVE_URL" -o "$ARCHIVE_FILE"
fi

mkdir -p "$(dirname "$LOCAL_ARCHIVE_CACHE")"
cp "$ARCHIVE_FILE" "$LOCAL_ARCHIVE_CACHE"

tar -xzf "$ARCHIVE_FILE" -C "$TMP_DIR"

IMPORT_ROOT="$TMP_DIR/gdal-${GDAL_TAG#v}"
if [[ ! -d "$IMPORT_ROOT" ]]; then
  IMPORT_ROOT="$TMP_DIR/gdal-${GDAL_TAG}"
fi

if [[ ! -d "$IMPORT_ROOT" ]]; then
  echo "Failed to locate extracted GDAL directory for tag $GDAL_TAG" >&2
  exit 1
fi

find "$SRC_DIR" -mindepth 1 -delete

copy_header_tree() {
  local rel_root="$1"
  local src_root="$IMPORT_ROOT/$rel_root"
  local dst_root="$SRC_DIR/$rel_root"
  if [[ ! -d "$src_root" ]]; then
    echo "Missing expected GDAL directory: $rel_root" >&2
    return 1
  fi
  mkdir -p "$dst_root"
  rsync -a --prune-empty-dirs \
    --include '*/' \
    --include '*.h' \
    --include '*.hpp' \
    --exclude '*' \
    "$src_root/" "$dst_root/"
}

# Keep this deterministic: mirror headers used by vendored OpenFileGDB low-level sources.
copy_header_tree "port"
copy_header_tree "gcore"
copy_header_tree "ogr"

mkdir -p "$SRC_DIR/gcore/gdal_version_full"

cat > "$SRC_DIR/port/cpl_config.h" <<'EOF'
/* Generated for openfgdb4j vendor-minimal build (macOS arm64). */

#ifndef CPL_CONFIG_H
#define CPL_CONFIG_H

#define SIZEOF_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_VOIDP 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_LONG_INT 8

#define HAVE_LOCALE_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_VSNPRINTF 1
#define HAVE_ICONV 1
#define HAVE_UINT128_T 1
#define HAVE_PTHREAD_MUTEX_RECURSIVE 1
#define HAVE_PTHREAD_ATFORK 1

#define HAVE_GCC_ATOMIC_BUILTINS 1
#define USE_GCC_VISIBILITY_FLAG 1

#define VSI_NEED_LARGEFILE64_SOURCE 1
#define UNIX_STDIO_64 1
#define VSI_FOPEN64 fopen
#define VSI_FTRUNCATE64 ftruncate
#define VSI_FSEEK64 fseeko
#define VSI_FTELL64 ftello
#define VSI_STAT64 stat
#define VSI_STAT64_T stat

#define DONT_DEPRECATE_SPRINTF 1
#define ICONV_CPP_CONST const

#endif
EOF

cat > "$SRC_DIR/gcore/gdal_version.h" <<'EOF'
/* Generated for openfgdb4j vendor-minimal build. */

#ifndef GDAL_VERSION_H_INCLUDED
#define GDAL_VERSION_H_INCLUDED

#define GDAL_VERSION_MAJOR 3
#define GDAL_VERSION_MINOR 12
#define GDAL_VERSION_REV 0
#define GDAL_VERSION_BUILD 0
#define GDAL_VERSION_NUM 3120000
#define GDAL_RELEASE_DATE 20251108
#define GDAL_RELEASE_NAME "3.12.0"

#endif
EOF

cat > "$SRC_DIR/gcore/gdal_version_full/gdal_version.h" <<'EOF'
/* Generated for openfgdb4j vendor-minimal build. */

#ifndef GDAL_VERSION_FULL_GDAL_VERSION_H_INCLUDED
#define GDAL_VERSION_FULL_GDAL_VERSION_H_INCLUDED

#define GDAL_RELEASE_NAME "3.12.0"
#define GDAL_RELEASE_DATE 20251108
#define GDAL_VERSION_NUM 3120000

#endif
EOF

typeset -a IMPORTED
IMPORTED=(${(f)"$(cd "$SRC_DIR" && find . -type f | sed 's|^./||' | sort)"})

{
  echo "# Imported from OSGeo/gdal tag $GDAL_TAG"
  echo "# Generated by scripts/import-gdal-core-minimal.sh"
  for rel in "${IMPORTED[@]}"; do
    echo "$rel"
  done
} > "$TP_DIR/IMPORTED_FILES.txt"

echo "Imported ${#IMPORTED[@]} GDAL core files from $GDAL_TAG"
